### ISSUE TITLE
Running tests on real-life Swagger files.

### ISSUE THREAD

**Issue by IvanGoncharov** [Trax-air/swagger-stub#1]
Hi @cyprieng,

Didn't found your email, so I opened Github issue instead :smile: 

Maybe you would be interested in testing your tools against 200+ real-life Swagger files:
https://github.com/APIs-guru/api-models
They are validated by [sway](https://github.com/apigee-127/sway/tree/master/docs#swagger-validation) and could acessed throug my [REST API](https://github.com/APIs-guru/api-models/blob/master/API.md)(no key needed).
I also have [public chat](https://gitter.im/APIs-guru/api-models) where you can ask any questions.

**Comment by cyprieng** [comment]
Thanks @IvanGoncharov, that's indeed a good idea. I don't know when I will do that, but I'll let you know.

**Comment by flavianh** [comment]
I'm closing this since this is more informative, but thanks for the heads up!

We also have a public chat BTW, it's the gitter link on our README ;)

**Comment by IvanGoncharov** [comment]
Hi @traxair,

Yes you right, I opened it because I didn't found @cyprieng email.
By the way, if you have public APIs, I can add them to my catalog.
I just need the link to API specification(Swagger, RAML, WADL, etc.).
