### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'next'

### ISSUE THREAD

**Issue by petkaze** [Trax-air/swagger-stub#8]
I have the following code that is more or less similar to the example given on the first page:

```
import pytest
from swagger_stub import swagger_stub

class TestStuff:

    @pytest.fixture
    def test_stub(self):
        return swagger_stub([('../mock_server/swagger/oauth.yaml', 'http://mytesthost.org')]).next()

    def test_swagger_stub(self, test_stub):
        assert 1 == 1
```

When using Python 3.6.2, I get the following error when I run the test method (it fails on line where the fixture is set up):
AttributeError: 'generator' object has no attribute 'next'

Any ideas?

**Comment by cyprieng** [comment]
`Generator.next()` has been renamed to `Generator.__next__()` in python 3.x

**Comment by petkaze** [comment]
Thanks, that solved it.
